databases:
  - name: test-app-db
    databaseName: test_db_production
    user: test_app_user

services:
  - type: web
    name: test-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
