databases:
  - name: portfolio-db
    databaseName: portfolio_db_production
    user: portfolio_user

services:
  - type: web
    name: portfolio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
